FROM apache/airflow:slim-3.1.7rc2-python3.13

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    librdkafka-dev \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    confluent-kafka \
    apache-airflow-providers-docker \
    apache-airflow-providers-apache-kafka
RUN pip install --no-cache-dir 'apache-airflow[postgres]'

WORKDIR /opt/airflow